version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
  webapp:
    image: hex:latest
    depends_on:
      - postgres
      - redis
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      STORE_MODE: sql
      API_TYPE: fast
    ports:
      - "5000:5000"