version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
  hex-app:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      STORE_MODE: sql
    ports:
      - "5000:5000"