name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make ideps

    - name: Run tests
      run: make test-cov
      env:
        REDIS_HOST: redis

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2